### ISSUE TITLE
Issues with new UI

### ISSUE THREAD

**Issue by amalik2** [CMPUT301F17T15/CIA#235]
Checkable list view for today's tasks does not update:
does not uncheck when cancelling creating a new habit event

Location text in createhabitevent is not large enough for some location names

Can't view habit details

Attached photo in profile doesn't show up

**Comment by amalik2** [comment]
first one is fixed now

**Comment by jessicaprt** [comment]
fixed most of it. photo in profile works for me

**Comment by amalik2** [comment]
it works now, so I guess they're all fixed
