### ISSUE TITLE
Crash when creating new habit

### ISSUE THREAD

**Issue by amalik2** [CMPUT301F17T15/CIA#69]
happens randomly

**Comment by shipinm1** [comment]
was it because the empty name or empty reason causing index error?

**Comment by amalik2** [comment]
no clue, it's only happened twice to me so far and both times were a few days ago. I think it might be fixed but I know the names and reasons weren't empty when it happened

**Comment by amalik2** [comment]
assuming this is solved since it has not reoccurred
